-- Your SQL goes here

CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  task_name VARCHAR NOT NULL,
  task_description VARCHAR DEFAULT NULL,
  task_score INTEGER DEFAULT 1 NOT NULL,
  admin_id SERIAL REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)