-- Your SQL goes here
CREATE TABLE IF NOT EXISTS nfts_comments (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  nft_id INTEGER NOT NULL,
  content VARCHAR NOT NULL,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);