[package]
name = "gem"
version = "0.1.3"
edition = "2021"
authors = ["wildonion <abarmardeatashyne@gmail.com>"]
description = "Conse Rust Backend Services"
homepage = "https://github.com/wildonion/gem/"
keywords = ["game","web","app", "rust", "crypto"]
license = "UNLICENSED"
repository = "https://github.com/wildonion/gem/"


[dependencies]
async-std = "1.12.0"
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.24.0"
actix-cors = "0.6.4"
actix-web = { version = "4", features = ["openssl"] }
actix-multipart = "0.6.0"
utoipa = { version = "3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }
diesel = { version = "2.0.4", features = ["postgres", "r2d2", "uuid", "chrono"] }
diesel-derive-enum = { version = "2.0.1", features = ["postgres"] }
rustls = "0.21.1"
redis = { version = "0.23.0", features = ["tokio-comp", "cluster-async", "json"] }
mongodb = "2"
futures = "0.3"
futures-util = "0.3"
rayon = "1"
uuid = { version = "1", features = ["serde", "v4"] }
borsh = "0.10"
serde_json = "1"
pretty_env_logger = "0.4"
env_logger = "0.10.0"
bytes = { version = "1", features = ["serde"] }
hex = "0.4"
dotenv = "0.15"
log = "0.4"
jsonwebtoken = "8"
rand = "0.8"
rand_chacha = "0.3.1"
rust-argon2 = "1"
rust-crypto = "0.2.36"
ring = "0.16.20"
sha2 = "0.10.6"
lazy_static = "1"
serde = {version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serenity = "0.11"
routerify-cors = "3"
routerify = "3"
routerify-multipart = "3"
sanitize-filename = "0.4.0"
async-trait = "0.1.64"
openai = "1.0.0-alpha.8"
once_cell = "1.17.1"
sysinfo = "0.28.4"
tokio-cron-scheduler = "0.9.4"
openssl = { version = "0.10", features = ["v110"] }

[[bin]]
name = "conse"
path = "core/app.rs"

[[bin]]
name = "dis-bot"
path = "core/contexts/bot/discord/bot.rs"

[[bin]]
name = "panel"
path = "core/contexts/panel/app.rs"

[[bin]]
name = "tests"
path = "test/main.rs"

[[bin]]
name = "argon2test"
path = "test/argon2test.rs"
