[package]
name = "conse"
version = "0.1.1"
edition = "2021"




[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
mongodb = "2"
futures = "0.3"
futures-util = "0.3"
rayon = "1"
rand = "0.8"
uuid = { version = "1", features = ["serde", "v4"] }
borsh = "0.9.3"
serde_json = "1"
pretty_env_logger = "0.4"
bytes = { version = "1", features = ["serde"] }
hex = "0.4"
dotenv = "0.15"
log = "0.4"
jsonwebtoken = "8"
rust-argon2 = "1"
lazy_static = "1"
serde = {version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
routerify-cors = "3"
routerify = "3"
routerify-multipart = "3.0.0"
sanitize-filename = "0.4.0"
async-trait = "0.1.58"





[[bin]]
name = "conse"
path = "src/main.rs"