[package]
name = "conse"
version = "0.1.1"
edition = "2021"




[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
mongodb = "2"
futures = "0.3"
futures-util = "0.3"
rayon = "1"
rand = "0.8"
uuid = { version = "1", features = ["serde", "v4"] }
borsh = "0.10"
serde_json = "1"
pretty_env_logger = "0.4"
bytes = { version = "1", features = ["serde"] }
hex = "0.4"
dotenv = "0.15"
log = "0.4"
jsonwebtoken = "8"
rust-argon2 = "1"
rust-crypto = "0.2.36"
ring = "0.16.20"
ed25519-dalek = "1.0.1"
lazy_static = "1"
serde = {version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
juniper = "0.15.11"
juniper_hyper = "0.8.0"
juniper_subscriptions = "0.16.0"
routerify-cors = "3"
routerify = "3"
routerify-multipart = "3"
routerify-websocket = "3.0.0"
sanitize-filename = "0.4.0"
async-trait = "0.1.64"
openai = "1.0.0-alpha.8"
mpl-token-metadata = "1.8.5"
mpl-candy-machine = "4.6.0"
solana-client-helpers = "1.1.0"
solana-client = "1.15.2" # this can be used to send rpc request to the solana blockchain
solana-sdk = "1.15.2"
spl-token = "3.5.0"
solana-transaction-status = "1.15.2"
anchor-client = "0.27.0" # this can be used to call deployed program methods using anchor through rpc 


[[bin]]
name = "conse"
path = "src/main.rs"