version: "3.8"


services:
  mongodb:
    image : mongo
    container_name: mongodb
    networks:
      - 'gem' 
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/root/gem/devops/database/mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  conse:
    build:
      dockerfile: 'devops/docker/gem/Dockerfile'
    container_name: conse
    ports:
      - '7439:7438'
    volumes:
      - './assets:/gem/assets'
    depends_on:
      - 'mongodb'
    links:
      - mongodb 
    networks:
      - 'gem'
  bot:
    build:
      dockerfile: 'devops/docker/bot/Dockerfile'
    container_name: wubot
    depends_on:
      - 'mongodb'
    links:
      - mongodb 
    networks:
      - 'gem'
  haproxy:
    image: eeacms/haproxy
    container_name: wubot
    depends_on:
      - conse
    ports:
      - "443:443"
      - "80:80"
      - "8404:8404"
      - "7440:7440"
    volumes:
      - devops/conf/haproxy.cfg:/usr/local/etc/haproxy
      - devops/openssl:/usr/local/etc/haproxy
    command: -c "haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg"
    environment:
      SERVER_IP: "${SERVER_IP}"
    networks:
      - 'gem'
networks:
  gem:
    driver: bridge
  