version: "3.8"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    command: --port 7442
    networks:
      - 'net'
    ports:
      - 7442:6379
    volumes:
      - ./devops/data/redis/:/data redis/redis-stack-server:latest
    restart: unless-stopped
  mongodb:
    image : mongo
    command: mongod --port 7441
    container_name: mongodb
    networks:
      - 'net' 
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./devops/data/mongodb/:/data/db
    ports:
      - 7441:27017
    restart: unless-stopped
  conse:
    build:
      dockerfile: './devops/docker/conse/Dockerfile'
    container_name: conse
    ports:
      - '7439:7438'
    volumes:
      - ./devops/data/assets/:/usr/src/app/assets/
      - '.:/usr/src/app'
    depends_on:
      - 'mongodb'
    links:
      - mongodb 
    networks:
      - 'net'
  bot:
    build:
      dockerfile: './devops/docker/bot/Dockerfile'
    container_name: catchup-bot
    volumes:
      - ./devops/data/openai-logs:/usr/src/app/openai-logs/
      - ./devops/data/gpt-logs:/usr/src/app/gpt-logs/
      - ./devops/data/error-kind:/usr/src/app/error-kind/
      - ./devops/data/rate-limiter:/usr/src/app/rate-limiter/
    networks:
      - 'net'
  panel:
    build:
      dockerfile: './devops/docker/panel/Dockerfile'
    container_name: conse
    ports:
      - '7443:7442'
    volumes:
      - '.:/usr/src/app' 
    networks:
      - 'net'
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    container_name: haproxy
    depends_on:
      - conse
    ports:
      - "443:443"
      - "80:80"
      - "8404:8404"
      - "7440:7440"
    volumes:
      - ./devops/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./devops/openssl/conse.pem:/usr/local/etc/conse.pem
    environment:
      SERVER_IP: "${SERVER_IP}"
    networks:
      - 'net'
networks:
  gem:
    driver: bridge
  