version: "3.8"


services:
  mongodb:
    image : mongo
    container_name: mongodb
    networks:
      - 'gem' 
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/root/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  #---------------------------------------
  #     Rust Docker Configuration
  #---------------------------------------
  # NOTE - due to the HAproxy DNS resolving 
  #        bug we've commented the following
  #        image since we'll run the rust server
  #        inside the VPS itself and run the HAproxy
  #        inside the docker so we can forward 
  #        rust server packets from the VPS ip
  #        to the specified and opened port 
  #        using HAproxy docker.
  # conse:
  #   build:
  #     dockerfile: './Dockerfile'
  #   container_name: conse
  #   ports:
  #     - '7439:7438'
  #   volumes:
  #     - './assets:/gem/assets'
  #   depends_on:
  #     - 'mongodb'
  #   links:
  #     - mongodb 
  #   networks:
  #     - 'gem'
networks:
  gem:
    driver: bridge
  