version: "3.8"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    networks:
      - 'net'
    ports:
      - 6379:6379
    volumes:
      - ./infra/data/redis/:/data redis/redis-stack-server:latest
    restart: unless-stopped 
  mongodb:
    image : mongo
    command: mongod --port 7441
    container_name: mongodb
    networks:
      - 'net' 
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./infra/data/mongodb/:/data/db
    ports:
      - 7441:27017
    restart: unless-stopped
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - 'net' 
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./infra/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 7543:8080
    depends_on:
      - 'postgres'
    links:
      - postgres 
    restart: always
  conse:
    build:
      dockerfile: './infra/docker/conse/Dockerfile'
    container_name: conse
    ports:
      - '7439:7438'
    depends_on:
      - 'mongodb'
    links:
      - mongodb 
    networks:
      - 'net'
  bot:
    build:
      dockerfile: './infra/docker/bot/Dockerfile'
    container_name: catchup-bot
    volumes:
      - ./infra/data/dis-bot-logs:/usr/src/app/logs/
    networks:
      - 'net'
  panel:
    build:
      dockerfile: './infra/docker/panel/Dockerfile'
    container_name: conse-panel
    ports:
      - '7443:7442'
    depends_on:
      - 'mongodb'
      - 'postgres'
    links:
      - mongodb 
      - postgres
    networks:
      - 'net'
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    container_name: haproxy
    depends_on:
      - conse
    ports:
      - "443:443"
      - "80:80"
      - "8404:8404"
      - "7440:7440"
    volumes:
      - ./infra/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./infra/cert/conse.pem:/usr/local/etc/conse.pem
    environment:
      SERVER_IP: "${SERVER_IP=$(hostname -I | awk '{print $1}')}"
    networks:
      - 'net'
networks:
  net:
    driver: bridge
  