version: "3.8"


services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    networks:
      - 'net'
    ports:
      - 6379:6379
    volumes:
      - ./devops/data/redis/:/data redis/redis-stack-server:latest
    restart: unless-stopped
  mongodb:
    image : mongo
    container_name: mongodb
    networks:
      - 'net' 
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./devops/data/mongodb/:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  conse:
    build:
      dockerfile: './devops/docker/conse/Dockerfile'
    container_name: conse
    ports:
      - '7439:7438'
    volumes:
      - assets
    depends_on:
      - 'mongodb'
    links:
      - mongodb 
    networks:
      - 'net'
  bot:
    build:
      dockerfile: './devops/docker/bot/Dockerfile'
    container_name: catchup-bot
    depends_on:
      - 'mongodb'
    volumes:
      - ./openai-logs:/usr/src/app/openai-logs
      - ./gpt-logs:/usr/src/app/gpt-logs
    links:
      - mongodb 
    networks:
      - 'net'
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    container_name: haproxy
    depends_on:
      - conse
    ports:
      - "443:443"
      - "80:80"
      - "8404:8404"
      - "7440:7440"
    volumes:
      - ./devops/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./devops/openssl/conse.pem:/usr/local/etc/conse.pem
    environment:
      SERVER_IP: "${SERVER_IP}"
    networks:
      - 'net'
networks:
  gem:
    driver: bridge
  