-- Your SQL goes here
CREATE TABLE users_mails (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  mail VARCHAR NOT NULL,
  code VARCHAR NOT NULL,
  exp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  vat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);