// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Person {
    pub name: String,
}

impl TableType for Person {
    const TABLE_NAME: &'static str = "Person";
    type ReducerEvent = super::ReducerEvent;
}

impl Person {
    #[allow(unused)]
    pub fn filter_by_name(name: String) -> TableIter<Self> {
        Self::filter(|row| row.name == name)
    }
}
