[features]
seeds = false
skip-lint = false

[programs.localnet]
ticket = "bArDn16ERF32oHbL3Qvbsfz55xkj1CdbPV8VYXJtCtk"
whitelist = "2YQmwuktcWmmhXXAzjizxzie3QWEkZC8HQ4ZnRtrKF7p"
ognils = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
ticket = "bArDn16ERF32oHbL3Qvbsfz55xkj1CdbPV8VYXJtCtk"
whitelist = "2YQmwuktcWmmhXXAzjizxzie3QWEkZC8HQ4ZnRtrKF7p"
ognils = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.mainnet]
ticket = "bArDn16ERF32oHbL3Qvbsfz55xkj1CdbPV8VYXJtCtk"
whitelist = "2YQmwuktcWmmhXXAzjizxzie3QWEkZC8HQ4ZnRtrKF7p"
ognils = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
# cluster = "mainnet"
wallet = "/home/wildonion/.config/solana/id.json"

[scripts]
test-ticket = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/ticket.ts"
test-whitelist = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/whitelist.ts"
test-ognils = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/ognils.ts"