[features]
seeds = false
skip-lint = false

[programs.localnet]
ticket = "DseCcTkkVGWnHnt6s8uMdcb5EDaduxaKxVfEu6aVkfLD"
whitelist = "4ZdXCpgo5wZTVbh1QV2yjcsiX1jCSzsqkfWeYwXwcAU2"

[programs.devnet]
ticket = "DseCcTkkVGWnHnt6s8uMdcb5EDaduxaKxVfEu6aVkfLD"
whitelist = "4ZdXCpgo5wZTVbh1QV2yjcsiX1jCSzsqkfWeYwXwcAU2"

[programs.mainnet]
ticket = "DseCcTkkVGWnHnt6s8uMdcb5EDaduxaKxVfEu6aVkfLD"
whitelist = "4ZdXCpgo5wZTVbh1QV2yjcsiX1jCSzsqkfWeYwXwcAU2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
# cluster = "mainnet"
wallet = "/home/wildonion/.config/solana/id.json"

[scripts]
test-ticket = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/ticket.ts"
test-whitelist = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/whitelist.ts"