[features]
seeds = false
skip-lint = false
[programs.localnet]
conse = "2dxHAp1hE9R4zieNEAVct4H5gC9xbYzdJ3DJnJ7EU62Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/wildonion/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
