[features]
seeds = false
skip-lint = false

[programs.localnet]
ticket = "DseCcTkkVGWnHnt6s8uMdcb5EDaduxaKxVfEu6aVkfLD"
whitelist = "HTx9H8pfWeCGXfe7Hfap6LkVXgQNLNh5CnCSNRscFyCk"

[programs.devnet]
ticket = "DseCcTkkVGWnHnt6s8uMdcb5EDaduxaKxVfEu6aVkfLD"
whitelist = "HTx9H8pfWeCGXfe7Hfap6LkVXgQNLNh5CnCSNRscFyCk"

[programs.mainnet]
ticket = "DseCcTkkVGWnHnt6s8uMdcb5EDaduxaKxVfEu6aVkfLD"
whitelist = "HTx9H8pfWeCGXfe7Hfap6LkVXgQNLNh5CnCSNRscFyCk"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "devnet"
# cluster = "mainnet"
wallet = "/home/wildonion/.config/solana/id.json"

[scripts]
test-ticket = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/ticket.ts"
test-whitelist = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/whitelist.ts"