-- Your SQL goes here
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  twitter_username VARCHAR NOT NULL,
  wallet_address VARCHAR NOT NULL,
  user_role VARCHAR NOT NULL,
  last_login TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)