-- Your SQL goes here

CREATE TYPE UserRole AS ENUM ('admin', 'dev', 'user');

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL,
  twitter_username VARCHAR DEFAULT NULL,
  facebook_username VARCHAR DEFAULT NULL,
  discord_username VARCHAR DEFAULT NULL,
  wallet_address VARCHAR DEFAULT NULL,
  user_role UserRole NOT NULL DEFAULT 'user',
  pswd VARCHAR NOT NULL,
  last_login TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)